// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Device struct {
	ID        string    `db:"id" json:"id"`
	Lat       float64   `db:"lat" json:"lat"`
	Lon       float64   `db:"lon" json:"lon"`
	Alt       float64   `db:"alt" json:"alt"`
	Speed     float64   `db:"speed" json:"speed"`
	Course    float64   `db:"course" json:"course"`
	Sats      int64     `db:"sats" json:"sats"`
	Hdop      float64   `db:"hdop" json:"hdop"`
	BatteryMv int64     `db:"battery_mv" json:"battery_mv"`
	Rssi      float64   `db:"rssi" json:"rssi"`
	Snr       float64   `db:"snr" json:"snr"`
	Online    int64     `db:"online" json:"online"`
	LastSeen  time.Time `db:"last_seen" json:"last_seen"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
